basic.forever(function () {
    JoyCar.light(ToggleSwitch.On)
    JoyCar.brakelight(ToggleSwitch.On)
    basic.pause(2000)
    JoyCar.light(ToggleSwitch.Off)
    JoyCar.brakelight(ToggleSwitch.Off)
    basic.pause(2000)
    JoyCar.reversinglight(ToggleSwitch.On)
    basic.pause(2000)
    JoyCar.reversinglight(ToggleSwitch.Off)
    basic.pause(2000)
})
