basic.forever(function () {
    JoyCar.light(ToggleSwitch.On)
    basic.pause(2000)
    JoyCar.light(ToggleSwitch.Off)
    basic.pause(2000)
    JoyCar.hazardlights(ToggleSwitch.On)
    basic.pause(2000)
    JoyCar.hazardlights(ToggleSwitch.Off)
    basic.pause(2000)
    JoyCar.reversinglight(ToggleSwitch.On)
    basic.pause(2000)
    JoyCar.reversinglight(ToggleSwitch.Off)
    basic.pause(2000)
    JoyCar.brakelight(ToggleSwitch.On)
    basic.pause(2000)
    JoyCar.brakelight(ToggleSwitch.Off)
    basic.pause(2000)
    JoyCar.indicator(ToggleSwitch.On, SensorLRSelection.Left)
    basic.pause(2000)
    JoyCar.indicator(ToggleSwitch.Off, SensorLRSelection.Left)
    basic.pause(2000)
    JoyCar.indicator(ToggleSwitch.On, SensorLRSelection.Right)
    basic.pause(2000)
    JoyCar.indicator(ToggleSwitch.Off, SensorLRSelection.Right)
    basic.pause(2000)
})
